logdir: runs
seed: 42
total_timesteps: 1000000
num_envs: 32
wandb_project: bryanoliveira/sliding_puzzles
disable_wandb: False

env:
  w: 2
  sparse_rewards: False
  win_reward: 10
  move_reward: -0.1
  invalid_move_reward: -1
  variation: onehot
  render_mode: rgb_array

  image_folder: single
  image_background: [0, 0, 0]
  image_size: [84, 84]