parent_config: base
ray:
  algorithm: PPO
  analysis_metric: episode_reward_mean
  config:
    num_workers: 8
    num_envs_per_worker: 4
    num_gpus: 1
    log_level: INFO
    evaluation_config:
      evaluation_interval: 1000
      evaluation_duration: 10
      evaluation_duration_unit: "episodes"
      render_env: True