parent_config: ray
env:
  variation: image
  image_size: [84, 84]
  w: 3
  h: 3
  shuffle_steps: 100
  sparse_rewards: False
  invalid_move_reward: -1
ray:
  algorithm: PPO
  config:
    num_workers: 0
    exploration_config:
      type: Curiosity
      eta: 0.2
      lr: 0.001
      feature_dim: 128
      feature_net_config:
          fcnet_hiddens: []
          fcnet_activation: relu
      sub_exploration:
          type: StochasticSampling